name: Build and Release Go App

on:
    workflow_dispatch:

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest, macos-latest, windows-latest]
                goos: [linux, darwin, windows]
                goarch: [amd64, arm64]

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: 1.23

            - name: Build
              run: |
                  mkdir -p dist
                  GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o dist/cre-${{ matrix.goos }}-${{ matrix.goarch }}

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: cre-${{ matrix.goos }}-${{ matrix.goarch }}
                  path: dist/cre-${{ matrix.goos }}-${{ matrix.goarch }}

    release:
        needs: build
        runs-on: ubuntu-latest
        steps:
            - name: Download artifacts
              uses: actions/download-artifact@v4
              with:
                  path: dist

            - name: Get Tags
              id: tag
              uses: ildug/get-tag-action@v1.0.3

            - name: Create GitHub Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ steps.tag.outputs.version }}
                  release_name: Release ${{ steps.tag.outputs.tag }}
                  draft: false
                  prerelease: false

            - name: Upload Release Asset
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ steps.create_release.outputs.upload_url }}
                  asset_path: dist/
                  asset_name: cre
                  asset_content_type: application/octet-stream
