name: Build and Release Go App

on:
    # workflow_dispatch:

    push:
        tags:
            - "v*.*.*"

jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ubuntu-latest]
                goos: [linux, darwin, windows]
                goarch: [amd64, arm64]

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Set up Go
              uses: actions/setup-go@v5
              with:
                  go-version: 1.23

            - name: Build
              run: |
                  go mod tidy
                  GOOS=${{ matrix.goos }} GOARCH=${{ matrix.goarch }} go build -o ./cre-${{ matrix.goos }}-${{ matrix.goarch }}-${{ github.ref_name }}

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: cre-${{ matrix.goos }}-${{ matrix.goarch }}-${{ github.ref_name }}
                  path: ./cre-${{ matrix.goos }}-${{ matrix.goarch }}-${{ github.ref_name }}

    release:
        needs: build
        runs-on: ubuntu-latest
        outputs:
            upload_url: ${{ steps.create_release.outputs.upload_url }}
        steps:
            - name: Create GitHub Release
              id: create_release
              uses: actions/create-release@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  tag_name: ${{ github.ref_name }}
                  release_name: ${{ github.ref_name }}
                  draft: false
                  prerelease: false

    upload:
        needs: release
        runs-on: ubuntu-latest
        strategy:
            matrix:
                goos: [linux, darwin, windows]
                goarch: [amd64, arm64]
        steps:
            - name: Download artifacts
              uses: actions/download-artifact@v4

            # - name: Get Tags
            #   id: tag
            #   uses: ildug/get-tag-action@v1.0.3

            - name: Upload Release Asset
              uses: actions/upload-release-asset@v1
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  upload_url: ${{ needs.release.outputs.upload_url }}
                  asset_path: ./cre-${{ matrix.goos }}-${{ matrix.goarch }}-${{ github.ref_name }}
                  asset_name: cre-${{ matrix.goos }}-${{ matrix.goarch }}-${{ github.ref_name }}
                  asset_content_type: application/octet-stream
